dotfiles
========
Jonathan Yu (@jawnsy) <jonathan.i.yu@gmail.com>

image:https://travis-ci.org/jawnsy/dotfiles.svg["Build Status", link="https://travis-ci.org/jawnsy/dotfiles"]

[intro]
Introduction
------------

***dotfiles*** is a collection of configuration files for bash, readline, ssh,
and other programs.  The files have been tested primarily on Debian Linux, but
should be applicable to other Linux distributions as well.

By publishing this repository, it is my hope that these files may be useful to
others, and that I might learn something through your contributions. Yes, you,
the lovely person reading this -- please send me your comments, complaints,
praise, rotten tomatoes, or whatever you'd like.

There are also references to many other great dotfile collections described at
https://dotfiles.github.io/

[usage]
Usage
-----

You can make use of the files in this distribution by copying individual
snippets to your configuration as desired, or replace your local configuration
with these files entirely using `sh install.sh`.

The files contained herein are organized relative to your user home directory
(`cd ~`) but can also be placed in `/etc/skel` to make them applicable to all
new users.

[license]
Copyright and License
---------------------

Anyone is free to copy, modify, publish, use, compile, sell, or distribute
this software, either in source code form or as a compiled binary, for any
purpose, commercial or non-commercial, and by any means.

The author or authors of this software dedicate any and all copyright interest
in the software to the public domain. We make this dedication for the benefit
of the public at large and to the detriment of our heirs and successors. We
intend this dedication to be an overt act of relinquishment in perpetuity of
all present and future rights to this software under copyright law.

The software is provided "AS IS", without warranty of any kind, express or
implied, including but not limited to the warranties of merchantability,
fitness for a particular purpose and noninfringement. In no event shall the
authors or copyright holders be liable for any claim, damages or other
liability, whether in an action of contract, tort or otherwise, arising from,
out of or in connection with the software or the use or other dealings in the
software.

[contributing]
Contributing
------------

Thank you for considering a contribution to this project.  Contributions (in
the form of bug reports, patches, or pull requests) are gratefully accepted by
the maintainer.

We ask that any code contributions be accompanied by a "sign-off" statement.
This can be done simply by using the `--signoff` flag for all git commits,
signifying compliance with the following **Developer Certificate of Origin**.

....
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
660 York Street, Suite 102,
San Francisco, CA 94110 USA

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
....
