name: build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  actions: none
  checks: none
  contents: read
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  linux:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: sh
    steps:
      - name: Cancel previous runs
        if: github.event_name == 'pull_request'
        uses: styfle/cancel-workflow-action@0.9.1

      - uses: actions/checkout@v3.1.0

      - name: Install dotfiles
        run: sh install.sh

      - name: Install dependencies
        run: |
          sudo apt-get install --no-install-recommends --yes \
            devscripts \
            shellcheck

      - name: Check Bash-isms
        run: checkbashisms install.sh

      - name: ShellCheck
        run: |
          shellcheck --shell=dash install.sh install-system.sh lib/*.sh
          shellcheck --shell=bash src/.bashrc.d/*.sh

      - name: Run .bashrc and show environment
        shell: bash
        run: |
          source ~/.bashrc
          env

      - name: Install system-level packages
        run: |
          yes | sudo sh install-system.sh
          sudo apt update

      - name: Ensure idempotency
        run:
          sh install.sh
          yes | sudo sh install-system.sh

  windows:
    runs-on: windows-2019
    defaults:
      run:
        shell: bash
    steps:
      - name: Cancel previous runs
        if: github.event_name == 'pull_request'
        uses: styfle/cancel-workflow-action@0.9.1

      - uses: actions/checkout@v3.1.0

      - name: Install dotfiles
        run: sh install.sh
        shell: bash

      - name: Ensure idempotency
        run: sh install.sh
        shell: bash
